# Generated by Django 3.0.10 on 2020-11-22 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('link', models.CharField(max_length=500)),
                ('image', models.CharField(max_length=500)),
                ('content', models.CharField(max_length=500)),
                ('date', models.CharField(max_length=500)),
            ],
        ),
    ]
