# Generated by Django 3.0.10 on 2020-11-27 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_directinginfo_dictrict'),
    ]

    operations = [
        migrations.CreateModel(
            name='DictricStatictisInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dictrict', models.CharField(max_length=500)),
                ('SoCaNhiem', models.IntegerField(default=0)),
                ('DangDieuTri', models.IntegerField(default=0)),
                ('Khoi', models.IntegerField(default=0)),
                ('TuVong', models.IntegerField(default=0)),
            ],
        ),
    ]
