# Generated by Django 3.0.10 on 2020-11-27 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_dictricstatictisinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dictricstatictisinfo',
            old_name='dictrict',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='dictricstatictisinfo',
            old_name='DangDieuTri',
            new_name='dangdieutri',
        ),
        migrations.RenameField(
            model_name='dictricstatictisinfo',
            old_name='Khoi',
            new_name='khoi',
        ),
        migrations.RenameField(
            model_name='dictricstatictisinfo',
            old_name='SoCaNhiem',
            new_name='socanhiem',
        ),
        migrations.RenameField(
            model_name='dictricstatictisinfo',
            old_name='TuVong',
            new_name='tuvong',
        ),
    ]
