# Generated by Django 3.0.10 on 2020-11-27 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20201127_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='directinginfo',
            old_name='dictrict',
            new_name='address',
        ),
    ]
