# Generated by Django 3.0.10 on 2020-12-01 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20201127_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectingNewsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('link', models.CharField(max_length=500)),
                ('image', models.CharField(max_length=500)),
                ('content', models.CharField(max_length=500)),
                ('date', models.CharField(max_length=500)),
            ],
        ),
    ]
