# Generated by Django 3.0.10 on 2020-12-01 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_directingnewsinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientinfo',
            name='id_popup',
            field=models.IntegerField(default=0),
        ),
    ]
