# Generated by Django 3.0.10 on 2020-12-01 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_patientinfo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientinfo',
            name='description',
            field=models.TextField(),
        ),
    ]
